openapi: 3.0.0
info:
  title: portal-poc
  description: "This is an example of API Dev portal."
  version: '1.0'
servers:
  - url: "https://1bpvqxwozb.execute-api.us-east-1.amazonaws.com"

paths:
  /apply:
    get:
      responses:
        default:
          description: "Default response for GET /apply"
          
  /echo:
    get:
      responses:
        '200':
          description: OK
          content:
            application/text:
              schema:
                type: string
    post:
      summary: Echoes back to supplied input
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Echo'
      responses:
        '200':
          description: OK
          content:
            application/text:
              schema:
                type: string
  /echo/{echoId}:
    delete:
      summary: Deletes an echo specified by echo Id
      parameters:
        - in: path
          name: echoId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/text:
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    
    
  schemas:
    Echo:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        

security:
  - bearerAuth: []
